version: '3'
services:
    nginx:
        image: nginx:1.17.10-alpine
        container_name: nginx
        network_mode: host
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        restart: unless-stopped